### ISSUE TITLE
Comma cannot be used or escaped for keyword/trigger

### ISSUE THREAD

**Issue by b02860de585071a2** [lochidev/TextToolsPro#19]
Trying to use a comma in the keyword does not work at all, however it *can* be used in the replacement text. 

Suppose we have the following espanso yml:

```
matches:
  - trigger: ',,t'
    replace: "test"
```

With this, the `,,t` would be interpreted literally. However in TT, this comes out as something like:

```
{"Trigger":",,t","Replace":"test","Vars":[],"Word":false}
```

(note the double quotes)

I might be missing something, but I have not found a way to interpret a keyword as a string literal. Importing a yml file (as mentioned above) does not work, most likely due to how it's converted into a json-friendly format.

Weirdly, other problematic characters are fine (`"`, `\`, `/`, etc).

System info:

- Version 6.9
- Android 14
- Pixel 8 Pro

**Comment by lochidev** [comment]
Thank you for the bug report. This is because I use these separators [' ', '\n', ','] to break a sentence into words. For ex:- word1 word2, word3\nword4 into an array like [word1, word2, word3, word4]. I then use the array to look in the dictionary for keywords. So, it's not great for triggers starting with those separators. I don't remember why added  the ',' into the separator list, may have been added to fix some big before 😅. I guess I will remove it next update and see if no bugs pop up. Of course, this is assuming I understood what you wanted exactly. I assumed you don't want ( ',,t' ) to trigger -> test, but instead want ( ,,t ) to trigger -> test. Ignore the brackets!

**Comment by b02860de585071a2** [comment]
> I don't remember why I added  the ',' into the separator list, may have been added to fix some bug before 😅. 

Probably some parsing thing, to make generating the json array easier on import? Considering that commas are fine in the expanded text, but not in keywords.


> I assumed you don't want 
> ```
> ',,t' to trigger -> test
> ``` 
> but instead want 
> ``` 
> ,,t to trigger -> test
> ``` 


Correct, I use `,,` as a leader for espanso on my actual PC (best way I've found to avoid accidentally triggering matches in normal use while still being fast to type). The single quotes are just there to prevent a syntax error.

**Comment by lochidev** [comment]
v6.9.1. Sorry this took way too long because I was trying to include bigger features in this release (forms support) but they need more testing.
